#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'flatstack',
  # path: '../chef-rails-cookbooks'
  git: 'git://github.com/fs/chef-rails-cookbooks.git'

cookbook 'nginx',
  git: 'git://github.com/jsierles/chef_cookbooks.git',
  path: 'nginx'

cookbook 'logentries',
  git: 'git://github.com/jagregory/chef-logentries.git'

cookbook 'ufw',
  git: 'git://github.com/opscode-cookbooks/ufw.git'

cookbook 'sysctl',
  git: 'git://github.com/DonorsChoose/chef-sysctl.git'
