#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'flatstack',
  # path: '../chef-rails-cookbooks'
  git: 'git://github.com/fs/chef-rails-cookbooks.git'

cookbook 'nginx',
  git: 'git://github.com/jsierles/chef_cookbooks.git',
  path: 'nginx'

cookbook 'logentries',
  git: 'git://github.com/jagregory/chef-logentries.git'

